export declare const backendApiKey = "ba9713548726a8b17bcd316e7044c20d";
export declare const backendApi = "https://wallet-api.sawe.dev/api/";
export declare const imagesURL: string;
export declare const bitqueryProxy: string;
export declare const tronWebProvider: {
    fullHost: string;
    solidityNode: string;
    eventServer: string;
};
export declare const tronUSDTContractAddress = "TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t";
export declare const ethWeb3Provider = "https://mainnet.infura.io/v3/522b462c9a1d45fb9b3b18b5fda51c05";
export declare const etherScanApi = "https://api-rinkeby.etherscan.io/api";
export declare const etherScanApiKey = "S18IGMPYTDRZ1CQJRHZIR5QE5F5AS2K16U";
export declare const etherUSDTContractAddress = "0xdac17f958d2ee523a2206206994597c13d831ec7";
export declare const etherGasPrice = "https://ethgasstation.info/api/ethgasAPI.json?api-key=d1c0caed8c46a0969ed707db1b8c6b08aab8861f223997cca266ee6ac5cc";
export declare const binanceWeb3Provider = "https://bsc-dataseed.binance.org/";
export declare const binanceUSDTContractAddress = "0xe9e7cea3dedca5984780bafc599bd69add087d56";
export declare const binanceScanApi = "https://api-testnet.bscscan.com/api";
export declare const solanaUSDTContractAddress = "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB";
export declare const polygonWeb3Provider = "https://polygon-rpc.com/";
export declare const polygonUSDTContractAddress = "0xc2132d05d31c914a87c6611c10748aeb04b58e8f";
export declare const polygonGasPrice = "https://gasstation-mainnet.matic.network";
export declare const etcWeb3Provider = "https://www.ethercluster.com/etc";
export declare const bitcoinSatoshisPerByte = 20;
export declare const bitcoinFeesURL = "https://bitcoinfees.earn.com/api/v1/fees/recommended";
export declare const dogeSatoshisPerByte = 206320;
export declare const litecoinSatoshisPerByte = 4000;
export declare const bitcoincashSatoshisPerByte = 1.3;
export declare const dashSatoshisPerByte = 400;
export declare const zcashSatoshisPerByte = 400;
export declare const rippleProvider = "wss://xrplcluster.com";
export declare const blockChairAPI = "https://api.blockchair.com/polkadot/raw/address/";
export declare const harmonyProvider = "https://api.harmony.one/";
export declare const harmonyUSDTContractAddress = "0x3c2b8be99c50593081eaa2a724f0b8285f5aba8f";
//# sourceMappingURL=providers.d.ts.map